export const CALL_STATES = {
	WAITING_FOR_OTHER_TO_PICKUP: "WAITING_FOR_OTHER_TO_PICKUP",
	WAITING_FOR_SELF_TO_PICKUP: "WAITING_FOR_SELF_TO_PICKUP",
	CONNECTED: "CONNECTED",

	// DISCONNECTED: "DISCONNECTED",
	OTHER_DECLINED_TO_ANSWER: "OTHER_DECLINED_TO_ANSWER",
	OTHER_CANCELED_CALL: "OTHER_CANCELED_CALL",
	OTHER_HANG_UP: "OTHER_HANG_UP",
}
